<a href="https://colab.research.google.com/github/anas1IA/meta_herstic_Krill_herd_optimization_library/blob/master/Code_Krill_Herd_Optimization_and_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### <center> <ins >Branch: 2IA </ins ></center>
# <center style= "color:red "> Training neural networks with Krill Herd.</center>
### <center> <ins >ANAS  NOURI <br><br>Pr. YASSER EL MADANI EL ALAMI </ins ></center>

# <font color='blue'><u> I. Libraries Used:</u></font> <br>

In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn.datasets import load_iris
import time as t

# <font color='blue'><u> II. Source Code:</u></font> <br>

In [ ]:
data= load_iris()
y = data.target

In [ ]:
y.shape
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
data1= data.data

In [ ]:
data1

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
data2 = np.concatenate((data1,y.reshape(150,1)), axis=1)

In [ ]:
np.unique(y)

array([0, 1, 2])

In [ ]:
m, n = data2.shape
print(m, n)

150 5


In [ ]:
#suffle data
np.random.shuffle(data2)
data_dev = data2[0:30].T
Y_dev = data_dev[-1]
X_dev = data_dev[:n-1]
# normalize X_dev
""" from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_dev = scaler.fit_transform(X_dev) """

data_train = data2[30:m].T
Y_train = data_train[-1]
X_train = data_train[:n-1]
_,m_train = X_train.shape

In [ ]:
Y_train = Y_train.astype(int)
Y_dev = Y_dev.astype(int)

Our NN will have a simple two-layer architecture. Input layer $a^{[0]}$ will have 784 units corresponding to the 4 pixels in each 28x28 input image. A hidden layer $a^{[1]}$ will have 10 units with ReLU activation, and finally our output layer $a^{[2]}$ will have 10 units corresponding to the ten digit classes with softmax activation.

**Forward propagation**


$$Z^{[1]} = W^{[1]} X + b^{[1]}$$
$$A^{[1]} = g_{\text{ReLU}}(Z^{[1]}))$$
$$Z^{[2]} = W^{[2]} A^{[1]} + b^{[2]}$$
$$A^{[2]} = g_{\text{softmax}}(Z^{[2]})$$

**Backward propagation**

$$dZ^{[2]} = A^{[2]} - Y$$
$$dW^{[2]} = \frac{1}{m} dZ^{[2]} A^{[1]T}$$
$$dB^{[2]} = \frac{1}{m} \Sigma {dZ^{[2]}}$$
$$dZ^{[1]} = W^{[2]T} dZ^{[2]} .* g^{[1]\prime} (z^{[1]})$$
$$dW^{[1]} = \frac{1}{m} dZ^{[1]} A^{[0]T}$$
$$dB^{[1]} = \frac{1}{m} \Sigma {dZ^{[1]}}$$

**Parameter updates**

$$W^{[2]} := W^{[2]} - \alpha dW^{[2]}$$
$$b^{[2]} := b^{[2]} - \alpha db^{[2]}$$
$$W^{[1]} := W^{[1]} - \alpha dW^{[1]}$$
$$b^{[1]} := b^{[1]} - \alpha db^{[1]}$$

**Vars and shapes**

Forward prop

- $A^{[0]} = X$: 784 x m
- $Z^{[1]} \sim A^{[1]}$: 10 x m
- $W^{[1]}$: 10 x 784 (as $W^{[1]} A^{[0]} \sim Z^{[1]}$)
- $B^{[1]}$: 10 x 1
- $Z^{[2]} \sim A^{[2]}$: 10 x m
- $W^{[1]}$: 10 x 10 (as $W^{[2]} A^{[1]} \sim Z^{[2]}$)
- $B^{[2]}$: 10 x 1

Backprop

- $dZ^{[2]}$: 10 x m ($~A^{[2]}$)
- $dW^{[2]}$: 10 x 10
- $dB^{[2]}$: 10 x 1
- $dZ^{[1]}$: 10 x m ($~A^{[1]}$)
- $dW^{[1]}$: 10 x 10
- $dB^{[1]}$: 10 x 1

In [ ]:
def init_params():
    W1 = np.random.rand(10, 4) - 0.5 # 10 neurons, 4 features
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 3) - 0.5 # 10 neurons, 3 probabilities using softmax
    b2 = np.random.rand(3, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = (W2.T).dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, int(Y.max()) + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2.T
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2

In [ ]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    #print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [ ]:
start_time = t.time()
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 150)
end_time = t.time()
print(" the expend time is " , end_time - start_time)

Iteration:  0
0.31666666666666665
Iteration:  10
0.35
Iteration:  20
0.35833333333333334
Iteration:  30
0.75
Iteration:  40
0.9083333333333333
Iteration:  50
0.65
Iteration:  60
0.6666666666666666
Iteration:  70
0.675
Iteration:  80
0.7333333333333333
Iteration:  90
0.7333333333333333
Iteration:  100
0.7666666666666667
Iteration:  110
0.7833333333333333
Iteration:  120
0.7916666666666666
Iteration:  130
0.8
Iteration:  140
0.8083333333333333
 the expend time is  0.06135988235473633


~85% accuracy on training set.

In [ ]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:, index, None]
    prediction = make_predictions(X_train[:, index, None], W1, b1, W2, b2)
    label = Y_train[index]
    print("Prediction: ", prediction)
    print("Label: ", label)

Let's look at a couple of examples:

In [ ]:
test_prediction(0, W1, b1, W2, b2)
test_prediction(1, W1, b1, W2, b2)
test_prediction(2, W1, b1, W2, b2)
test_prediction(3, W1, b1, W2, b2)

Prediction:  [1]
Label:  1
Prediction:  [1]
Label:  1
Prediction:  [1]
Label:  1
Prediction:  [1]
Label:  1


Finally, let's find the accuracy on the dev set:

In [ ]:
dev_predictions = make_predictions(X_dev, W1, b1, W2, b2)
get_accuracy(dev_predictions, Y_dev)

0.8666666666666667

Still 90% accuracy, so our model generalized from the training data pretty well.

## Train using Krill Herd algorithm


In [ ]:
def weights2vector(W1, b1, W2, b2):
    return np.concatenate((W1.reshape(W1.size), b1.reshape(b1.size), W2.reshape(W2.size), b2.reshape(b2.size)))
def vector2weights(vector):
    W1_start = 0
    W1_end = 10 * 4
    b1_end = W1_end + 10
    W2_end = b1_end + 10 * 3
    W1 = vector[W1_start:W1_end].reshape(10, 4)
    b1 = vector[W1_end:b1_end].reshape(10, 1)
    W2 = vector[b1_end:W2_end].reshape(10, 3)
    b2 = vector[W2_end:].reshape(3, 1)
    return W1, b1, W2, b2

In [ ]:
x = weights2vector(W1, b1, W2, b2)
x.shape

(83,)

In [ ]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    #print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [ ]:
start_time = t.time()
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 200)
end_time = t.time()
print(" the expend time is " , end_time - start_time)

Iteration:  0
0.35
Iteration:  10
0.6916666666666667
Iteration:  20
0.7
Iteration:  30
0.7416666666666667
Iteration:  40
0.8083333333333333
Iteration:  50
0.9166666666666666
Iteration:  60
0.675
Iteration:  70
0.6666666666666666
Iteration:  80
0.6916666666666667
Iteration:  90
0.7333333333333333
Iteration:  100
0.7333333333333333
Iteration:  110
0.7833333333333333
Iteration:  120
0.7833333333333333
Iteration:  130
0.7916666666666666
Iteration:  140
0.7833333333333333
Iteration:  150
0.8083333333333333
Iteration:  160
0.8083333333333333
Iteration:  170
0.8166666666666667
Iteration:  180
0.8416666666666667
Iteration:  190
0.8583333333333333
 the expend time is  0.08306145668029785


In [ ]:
W1.shape,W2.shape,b1.shape,b2.shape

((10, 4), (10, 3), (10, 1), (3, 1))

In [ ]:

class KrillHerd:
    def __init__(self, population_size=15, min_values=[-100, -100], max_values=[100, 100], generations=355, c_t=1, target_function=None, verbose=True, start_init=None, target_value=None):
        self.population_size = population_size
        self.min_values = np.array(min_values)
        self.max_values = np.array(max_values)
        self.generations = generations
        self.c_t = np.clip(c_t, 0, 2)
        self.target_function = target_function if target_function else self.target_function
        self.verbose = verbose
        self.start_init = start_init
        self.target_value = target_value

    @staticmethod
    def target_function(x):
        return

    def initialize_variables(self):
        dim = len(self.min_values)
        if self.start_init is not None:
            start_init = np.atleast_2d(self.start_init)
            n_rows = self.population_size - start_init.shape[0]
            if n_rows > 0:
                rows = np.random.uniform(self.min_values, self.max_values, (n_rows, dim))
                start_init = np.vstack((start_init[:, :dim], rows))
            else:
                start_init = start_init[:self.population_size, :dim]
            fitness_values = self.target_function(start_init) if hasattr(self.target_function, 'vectorized') else np.apply_along_axis(self.target_function, 1, start_init)
            population = np.hstack((start_init, fitness_values[:, np.newaxis] if not hasattr(self.target_function, 'vectorized') else fitness_values))
        else:
            population = np.random.uniform(self.min_values, self.max_values, (self.population_size, dim))
            fitness_values = self.target_function(population) if hasattr(self.target_function, 'vectorized') else np.apply_along_axis(self.target_function, 1, population)
            population = np.hstack((population, fitness_values[:, np.newaxis] if not hasattr(self.target_function, 'vectorized') else fitness_values))
        return population

    @staticmethod
    def build_distance_matrix(population):
        a = np.copy(population[:, :-1])
        b = a.reshape(np.prod(a.shape[:-1]), 1, a.shape[-1])
        return np.sqrt(np.einsum('ijk,ijk->ij', b - a, b - a)).squeeze()

    def motion_induced_process(self, population, population_n, best_ind, worst_ind, c):
        n_max = 0.01
        num_features = population.shape[1] - 1
        dtm = self.build_distance_matrix(population)
        np.fill_diagonal(dtm, float('+inf'))
        for i in range(population.shape[0]):
            idx = np.argpartition(dtm[i, :], int(num_features / 5))[:int(num_features / 5)]
            k_ij = np.sum((population_n[i, -1] - population_n[idx, -1]) / (-best_ind[-1] + worst_ind[-1] + 1e-16))
            x_ij = np.sum((population_n[idx, :-1] - population_n[i, :-1]) / (dtm[i, idx][:, np.newaxis] + 1e-16), axis=0)
            a_iL = k_ij * x_ij
            rand = np.random.rand()
            a_i = a_iL + 2 * (rand + c) * best_ind[-1] * best_ind[:-1]
            w_vector = np.random.rand(num_features)
            population_n[i, :-1] = np.clip(a_i * n_max + w_vector * population_n[i, :-1], self.min_values, self.max_values)
            population_n[i, -1] = self.target_function(population_n[i, :-1])
        return population_n

    def foraging_motion(self, population, population_f, best_ind, c):
        num_features = len(self.min_values)
        x_if = best_ind[:-1] * (1 / (best_ind[-1] + 1e-16))
        x_if = x_if / (1 / (best_ind[-1] + 1e-16))
        k_if = self.target_function(x_if)
        v_f = 0.02
        c_f = 2 * (1 - c)
        b_i = c_f * k_if * x_if + best_ind[-1] * best_ind[:-1]
        for i in range(population.shape[0]):
            w_vector = np.random.rand(num_features)
            population_f[i, :-1] = np.clip(v_f * b_i + w_vector * population_f[i, :-1], self.min_values, self.max_values)
            population_f[i, -1] = self.target_function(population_f[i, :-1])
        return population_f

    def physical_difusion(self, population, c):
        num_features = population.shape[1] - 1
        d_max = np.random.uniform(0.002, 0.010, size=(population.shape[0], 1))
        random_diffusion = np.random.uniform(-1, 1, size=(population.shape[0], num_features))
        population_d = np.zeros_like(population)
        population_d[:, :-1] = np.clip(d_max * random_diffusion * (1 - c), self.min_values, self.max_values)
        for i in range(population.shape[0]):
            population_d[i, -1] = self.target_function(population_d[i, :-1])
        return population_d

    def update_position(self, population, population_n, population_f, population_d, c):
        old_population = np.copy(population)
        delta_t = c * np.sum(self.max_values - self.min_values)
        population[:, :-1] = np.clip(population[:, :-1] + delta_t * (population_n[:, :-1] + population_f[:, :-1] + population_d[:, :-1]), self.min_values, self.max_values)
        population[:, -1] = np.apply_along_axis(self.target_function, 1, population[:, :-1])
        population = np.vstack([old_population, population, population_n, population_f, population_d])
        population = population[population[:, -1].argsort()]
        return population[:old_population.shape[0], :]

    @staticmethod
    def fitness_function(population):
        fitness = np.zeros((population.shape[0], 2))
        for i in range(fitness.shape[0]):
            fitness[i, 0] = 1 / (1 + population[i, -1] + abs(population[:, -1].min()))
        fit_sum = fitness[:, 0].sum()
        fitness[0, 1] = fitness[0, 0]
        for i in range(1, fitness.shape[0]):
            fitness[i, 1] = fitness[i, 0] + fitness[i - 1, 1]
        for i in range(fitness.shape[0]):
            fitness[i, 1] = fitness[i, 1] / fit_sum
        return fitness

    @staticmethod
    def roulette_wheel(fitness):
        ix = 0
        random = np.random.rand()
        for i in range(fitness.shape[0]):
            if random <= fitness[i, 1]:
                ix = i
                break
        return ix

    def breeding(self, population, fitness, mu, elite):
        offspring = np.copy(population)
        if elite > 0:
            preserve = np.copy(population[population[:, -1].argsort()])
            for i in range(elite):
                for j in range(offspring.shape[1]):
                    offspring[i, j] = preserve[i, j]
        for i in range(elite, offspring.shape[0]):
            parent_1, parent_2 = self.roulette_wheel(fitness), self.roulette_wheel(fitness)
            while parent_1 == parent_2:
                parent_2 = np.random.choice(len(population) - 1)
            for j in range(offspring.shape[1] - 1):
                rand = np.random.rand()
                rand_b = np.random.rand()
                rand_c = np.random.rand()
                b_offspring = 2 * rand_b if rand <= 0.5 else 1 / (2 * (1 - rand_b))
                b_offspring = b_offspring ** (1 / (mu + 1))
                offspring[i, j] = np.clip(
                    ((1 + b_offspring) * population[parent_1, j] + (1 - b_offspring) * population[parent_2, j]) / 2
                    if rand_c >= 0.5 else
                    ((1 - b_offspring) * population[parent_1, j] + (1 + b_offspring) * population[parent_2, j]) / 2,
                    self.min_values[j], self.max_values[j])
            offspring[i, -1] = self.target_function(offspring[i, :-1])
        return offspring

    def mutation(self, offspring, mutation_rate, eta):
        for i in range(offspring.shape[0]):
            for j in range(offspring.shape[1] - 1):
                probability = np.random.rand()
                if probability < mutation_rate:
                    rand = np.random.rand()
                    rand_d = np.random.rand()
                    d_mutation = 2 * rand_d if rand <= 0.5 else 2 * (1 - rand_d)
                    d_mutation = d_mutation ** (1 / (eta + 1)) - 1 if rand <= 0.5 else 1 - d_mutation ** (1 / (eta + 1))
                    offspring[i, j] = np.clip(offspring[i, j] + d_mutation, self.min_values[j], self.max_values[j])
            offspring[i, -1] = self.target_function(offspring[i, :-1])
        return offspring

    def run(self):
        population = self.initialize_variables()
        best_ind = np.copy(population[np.argmin(population[:, -1]), :])
        worst_ind = np.copy(population[np.argmax(population[:, -1]), :])
        population_n = np.zeros_like(population)
        population_f = np.copy(population)
        population_d = np.zeros_like(population)
        count = 0

        while count <= self.generations:
            c = count / self.generations
            if self.verbose:
                print('Generation =', count, 'f(x) =', best_ind[-1])
            population_n = self.motion_induced_process(population, population_n, best_ind, worst_ind, c)
            population_f = self.foraging_motion(population, population_f, best_ind, c)
            population_d = self.physical_difusion(population, c)
            population = self.update_position(population, population_n, population_f, population_d, self.c_t)
            if np.random.rand() <= 0.2:
                fitness = self.fitness_function(population)
                offspring = self.breeding(population, fitness, 1, 1)
                population = self.mutation(offspring, 0.05, 1)
            best_loc = population[np.argmin(population[:, -1]), :]
            worst_ind = np.copy(population[np.argmax(population[:, -1]), :])
            if best_loc[-1] < best_ind[-1]:
                best_ind = np.copy(best_loc)
            if self.target_value is not None and best_ind[-1] <= self.target_value:
                break
            count += 1

        return best_ind




In [ ]:

def example_target_function(x):
    return np.sum(x**2)

kha = KrillHerd(target_function=example_target_function, verbose=True)
best_solution = kha.run()
print("Best Solution:", best_solution)
print(best_solution[:-1])

Generation = 0 f(x) = 145.5846568857524
Generation = 1 f(x) = 4.183349840196711e-07
Generation = 2 f(x) = 2.6439474722338383e-07
Generation = 3 f(x) = 2.6439474722338383e-07
Generation = 4 f(x) = 2.422227576135988e-08
Generation = 5 f(x) = 2.422227576135988e-08
Generation = 6 f(x) = 2.422227576135988e-08
Generation = 7 f(x) = 1.605285107328271e-08
Generation = 8 f(x) = 4.954585147067925e-11
Generation = 9 f(x) = 4.353447037400812e-11
Generation = 10 f(x) = 1.0547988996196503e-12
Generation = 11 f(x) = 1.933423157586579e-14
Generation = 12 f(x) = 9.287104822968037e-15
Generation = 13 f(x) = 5.695200839919719e-15
Generation = 14 f(x) = 3.89630801359651e-16
Generation = 15 f(x) = 4.110518232032335e-18
Generation = 16 f(x) = 1.100021037546526e-18
Generation = 17 f(x) = 1.180613511127675e-20
Generation = 18 f(x) = 6.901545214636398e-21
Generation = 19 f(x) = 3.702832285043552e-23
Generation = 20 f(x) = 1.768985271532077e-23
Generation = 21 f(x) = 9.52761659540322e-25
Generation = 22 f(x) = 

In [ ]:
import numpy as np

# Define the objective function
def objective_function(X):
    """Objective function to be minimized."""
    W1, b1, W2, b2 = vector2weights(X)
    Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X_train)
    predictions = np.argmax(A2, axis=0)
    return -np.sum(predictions == Y_train) / Y_train.size  # Negate accuracy since we are minimizing

class KrillHerd:
    def __init__(self, population_size=15, min_values=None, max_values=None, generations=500, c_t=1, target_function=None,target_value=None , verbose=True):
        self.population_size = population_size
        self.min_values = np.array(min_values)
        self.max_values = np.array(max_values)
        self.generations = generations
        self.target_value = target_value
        self.c_t = np.clip(c_t, 0, 2)
        self.target_function = target_function if target_function else self.target_function
        self.verbose = verbose

    @staticmethod
    def target_function(x):
        return

    def initialize_variables(self):
        dim = len(self.min_values)
        population = np.random.uniform(self.min_values, self.max_values, (self.population_size, dim))
        fitness_values = np.apply_along_axis(self.target_function, 1, population)
        population = np.hstack((population, fitness_values[:, np.newaxis]))
        return population

    @staticmethod
    def build_distance_matrix(population):
        a = np.copy(population[:, :-1])
        b = a.reshape(np.prod(a.shape[:-1]), 1, a.shape[-1])
        return np.sqrt(np.einsum('ijk,ijk->ij', b - a, b - a)).squeeze()

    def motion_induced_process(self, population, population_n, best_ind, worst_ind, c):
        n_max = 0.01
        num_features = population.shape[1] - 1
        dtm = self.build_distance_matrix(population)
        np.fill_diagonal(dtm, float('+inf'))
        for i in range(population.shape[0]):
            idx = np.argpartition(dtm[i, :], int(num_features / 5))[:int(num_features / 5)]
            k_ij = np.sum((population_n[i, -1] - population_n[idx, -1]) / (-best_ind[-1] + worst_ind[-1] + 1e-16))
            x_ij = np.sum((population_n[idx, :-1] - population_n[i, :-1]) / (dtm[i, idx][:, np.newaxis] + 1e-16), axis=0)
            a_iL = k_ij * x_ij
            rand = np.random.rand()
            a_i = a_iL + 2 * (rand + c) * best_ind[-1] * best_ind[:-1]
            w_vector = np.random.rand(num_features)
            population_n[i, :-1] = np.clip(a_i * n_max + w_vector * population_n[i, :-1], self.min_values, self.max_values)
            population_n[i, -1] = self.target_function(population_n[i, :-1])
        return population_n

    def foraging_motion(self, population, population_f, best_ind, c):
        num_features = len(self.min_values)
        x_if = best_ind[:-1] * (1 / (best_ind[-1] + 1e-16))
        x_if = x_if / (1 / (best_ind[-1] + 1e-16))
        k_if = self.target_function(x_if)
        v_f = 0.02
        c_f = 2 * (1 - c)
        b_i = c_f * k_if * x_if + best_ind[-1] * best_ind[:-1]
        for i in range(population.shape[0]):
            w_vector = np.random.rand(num_features)
            population_f[i, :-1] = np.clip(v_f * b_i + w_vector * population_f[i, :-1], self.min_values, self.max_values)
            population_f[i, -1] = self.target_function(population_f[i, :-1])
        return population_f

    def physical_difusion(self, population, c):
        num_features = population.shape[1] - 1
        d_max = np.random.uniform(0.002, 0.010, size=(population.shape[0], 1))
        random_diffusion = np.random.uniform(-1, 1, size=(population.shape[0], num_features))
        population_d = np.zeros_like(population)
        population_d[:, :-1] = np.clip(d_max * random_diffusion * (1 - c), self.min_values, self.max_values)
        for i in range(population.shape[0]):
            population_d[i, -1] = self.target_function(population_d[i, :-1])
        return population_d

    def update_position(self, population, population_n, population_f, population_d, c):
        old_population = np.copy(population)
        delta_t = c * np.sum(self.max_values - self.min_values)
        population[:, :-1] = np.clip(population[:, :-1] + delta_t * (population_n[:, :-1] + population_f[:, :-1] + population_d[:, :-1]), self.min_values, self.max_values)
        population[:, -1] = np.apply_along_axis(self.target_function, 1, population[:, :-1])
        population = np.vstack([old_population, population, population_n, population_f, population_d])
        population = population[population[:, -1].argsort()]
        return population[:old_population.shape[0], :]

    @staticmethod
    def fitness_function(population):
        fitness = np.zeros((population.shape[0], 2))
        for i in range(fitness.shape[0]):
            fitness[i, 0] = 1 / (1 + population[i, -1] + abs(population[:, -1].min()))
        fit_sum = fitness[:, 0].sum()
        fitness[0, 1] = fitness[0, 0]
        for i in range(1, fitness.shape[0]):
            fitness[i, 1] = fitness[i, 0] + fitness[i - 1, 1]
        for i in range(fitness.shape[0]):
            fitness[i, 1] = fitness[i, 1] / fit_sum
        return fitness

    @staticmethod
    def roulette_wheel(fitness):
        ix = 0
        random = np.random.rand()
        for i in range(fitness.shape[0]):
            if random <= fitness[i, 1]:
                ix = i
                break
        return ix

    def breeding(self, population, fitness, mu, elite):
        offspring = np.copy(population)
        if elite > 0:
            preserve = np.copy(population[population[:, -1].argsort()])
            for i in range(elite):
                for j in range(offspring.shape[1]):
                    offspring[i, j] = preserve[i, j]
        for i in range(elite, offspring.shape[0]):
            parent_1, parent_2 = self.roulette_wheel(fitness), self.roulette_wheel(fitness)
            while parent_1 == parent_2:
                parent_2 = np.random.choice(len(population) - 1)
            for j in range(offspring.shape[1] - 1):
                rand = np.random.rand()
                rand_b = np.random.rand()
                rand_c = np.random.rand()
                b_offspring = 2 * rand_b if rand <= 0.5 else 1 / (2 * (1 - rand_b))
                b_offspring = b_offspring ** (1 / (mu + 1))
                offspring[i, j] = np.clip(
                    ((1 + b_offspring) * population[parent_1, j] + (1 - b_offspring) * population[parent_2, j]) / 2
                    if rand_c >= 0.5 else
                    ((1 - b_offspring) * population[parent_1, j] + (1 + b_offspring) * population[parent_2, j]) / 2,
                    self.min_values[j],
                    self.max_values[j]
                )
            offspring[i, -1] = self.target_function(offspring[i, :-1])
        return offspring

    def mutation(self, offspring, mutation_rate, eta):
        for i in range(offspring.shape[0]):
            for j in range(offspring.shape[1] - 1):
                probability = np.random.rand()
                if probability < mutation_rate:
                    rand = np.random.rand()
                    rand_d = np.random.rand()
                    d_mutation = 2 * rand_d if rand <= 0.5 else 2 * (1 - rand_d)
                    d_mutation = d_mutation ** (1 / (eta + 1)) - 1 if rand <= 0.5 else 1 - d_mutation ** (1 / (eta + 1))
                    offspring[i, j] = np.clip(offspring[i, j] + d_mutation, self.min_values[j], self.max_values[j])
            offspring[i, -1] = self.target_function(offspring[i, :-1])
        return offspring

    def run(self):
        population = self.initialize_variables()
        best_ind = np.copy(population[np.argmin(population[:, -1]), :])
        worst_ind = np.copy(population[np.argmax(population[:, -1]), :])
        population_n = np.zeros_like(population)
        population_f = np.copy(population)
        population_d = np.zeros_like(population)
        count = 0

        while count <= self.generations:
            c = count / self.generations
            if self.verbose:
                print('Generation =', count, 'f(x) =', best_ind[-1])
            population_n = self.motion_induced_process(population, population_n, best_ind, worst_ind, c)
            population_f = self.foraging_motion(population, population_f, best_ind, c)
            population_d = self.physical_difusion(population, c)
            population = self.update_position(population, population_n, population_f, population_d, self.c_t)
            if np.random.rand() <= 0.2:
                fitness = self.fitness_function(population)
                offspring = self.breeding(population, fitness, 1, 1)
                population = self.mutation(offspring, 0.05, 1)
            best_loc = population[np.argmin(population[:, -1]), :]
            worst_ind = np.copy(population[np.argmax(population[:, -1]), :])
            if best_loc[-1] < best_ind[-1]:
                best_ind = np.copy(best_loc)
            if self.target_value is not None and best_ind[-1] <= self.target_value:
                break
            count += 1

        return best_ind





In [ ]:
# def new_objective_function(x):
#     return x[0]**2 + x[1]**2 + x[2]**2

# Define the problem-specific parameters
num_dimensions = 40 + 10 + 30 + 3  # Adjust this based on your vectorized weights dimensions
min_values = [-100] * num_dimensions
max_values = [100] * num_dimensions

# Create the Krill Herd Algorithm instance
kha = KrillHerd(
    population_size=100,
    min_values=min_values,
    max_values=max_values,
    generations=200,
    target_function=objective_function,
    verbose=True
)
start_1 = t.time()
# Run the optimization
best_solution = kha.run()
print(" the Krill herd algorithm expended " , t.time()-start_1)
print("Best Solution:", best_solution[:-1])
print("Best Objective Value (Accuracy):", -best_solution[-1])  # Negate back to get accuracya

Generation = 0 f(x) = -0.85
Generation = 1 f(x) = -0.85


<ipython-input-502-b705f9cde714>:12: RuntimeWarning: overflow encountered in exp
  A = np.exp(Z) / sum(np.exp(Z))
<ipython-input-502-b705f9cde714>:12: RuntimeWarning: invalid value encountered in divide
  A = np.exp(Z) / sum(np.exp(Z))


Generation = 2 f(x) = -0.85
Generation = 3 f(x) = -0.85
Generation = 4 f(x) = -0.85
Generation = 5 f(x) = -0.85
Generation = 6 f(x) = -0.85
Generation = 7 f(x) = -0.85
Generation = 8 f(x) = -0.85
Generation = 9 f(x) = -0.85
Generation = 10 f(x) = -0.85
Generation = 11 f(x) = -0.85
Generation = 12 f(x) = -0.85
Generation = 13 f(x) = -0.85
Generation = 14 f(x) = -0.85
Generation = 15 f(x) = -0.85
Generation = 16 f(x) = -0.85
Generation = 17 f(x) = -0.85
Generation = 18 f(x) = -0.85
Generation = 19 f(x) = -0.85
Generation = 20 f(x) = -0.85
Generation = 21 f(x) = -0.85
Generation = 22 f(x) = -0.85
Generation = 23 f(x) = -0.85
Generation = 24 f(x) = -0.85
Generation = 25 f(x) = -0.85
Generation = 26 f(x) = -0.85
Generation = 27 f(x) = -0.85
Generation = 28 f(x) = -0.85
Generation = 29 f(x) = -0.85
Generation = 30 f(x) = -0.85
Generation = 31 f(x) = -0.85
Generation = 32 f(x) = -0.85
Generation = 33 f(x) = -0.85
Generation = 34 f(x) = -0.85
Generation = 35 f(x) = -0.85
Generation = 36 f(x) =

In [ ]:
import numpy as np

# Given array
array = np.array(best_solution[:-1])

# Min-max normalization
normalized_array = (array - np.min(array)) / (np.max(array) - np.min(array))

print("Normalized Array:")
print(normalized_array)


Normalized Array:
[0.00000000e+00 1.00000000e+00 9.32499814e-01 3.36760573e-02
 1.00000000e+00 1.00000000e+00 1.00000000e+00 1.27595191e-01
 1.00000000e+00 5.92017410e-01 0.00000000e+00 0.00000000e+00
 9.06278566e-01 1.29369825e-02 1.00000000e+00 1.00000000e+00
 1.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00
 9.39038413e-01 1.00000000e+00 7.10542736e-17 7.10542736e-17
 0.00000000e+00 1.00000000e+00 9.02194964e-01 1.18175584e-01
 0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
 0.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
 0.00000000e+00 1.00000000e+00 1.00000000e+00 9.64571101e-01
 0.00000000e+00 0.00000000e+00 9.37553531e-02 0.00000000e+00
 0.00000000e+00 1.00000000e+00 9.31666305e-01 1.00000000e+00
 8.03157488e-01 2.26917654e-02 3.41477468e-02 0.00000000e+00
 1.00000000e+00 1.00000000e+00 9.11729278e-01 1.00000000e+00
 1.00000000e+00 4.18069830e-02 0.00000000e+00 0.00000000e+00
 9.14943850e-04 8.15737604e-02 1.00000000e+00 0.00000000e+00
 0.000

In [ ]:
 W1,b1,W2,b2 = vector2weights(normalized_array)
 W1,b1,W2,b2

(array([[0.00000000e+00, 1.00000000e+00, 9.32499814e-01, 3.36760573e-02],
        [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.27595191e-01],
        [1.00000000e+00, 5.92017410e-01, 0.00000000e+00, 0.00000000e+00],
        [9.06278566e-01, 1.29369825e-02, 1.00000000e+00, 1.00000000e+00],
        [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [9.39038413e-01, 1.00000000e+00, 7.10542736e-17, 7.10542736e-17],
        [0.00000000e+00, 1.00000000e+00, 9.02194964e-01, 1.18175584e-01],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
        [0.00000000e+00, 1.00000000e+00, 1.00000000e+00, 9.64571101e-01]]),
 array([[0.        ],
        [0.        ],
        [0.09375535],
        [0.        ],
        [0.        ],
        [1.        ],
        [0.9316663 ],
        [1.        ],
        [0.80315749],
        [0.02269177]]),
 array([[3.41477468e-02, 0.00000000e

In [ ]:
 W1,b1,W2,b2 = vector2weights(best_solution[:-1])
 W1,b1,W2,b2

(array([[-100.        ,  100.        ,   86.49996282,  -93.26478855],
        [ 100.        ,  100.        ,  100.        ,  -74.4809617 ],
        [ 100.        ,   18.40348205, -100.        , -100.        ],
        [  81.25571323,  -97.4126035 ,  100.        ,  100.        ],
        [ 100.        , -100.        , -100.        ,  100.        ],
        [  87.80768267,  100.        , -100.        , -100.        ],
        [-100.        ,  100.        ,   80.43899278,  -76.36488314],
        [-100.        , -100.        ,  100.        , -100.        ],
        [-100.        ,  100.        ,  100.        ,  100.        ],
        [-100.        ,  100.        ,  100.        ,   92.9142202 ]]),
 array([[-100.        ],
        [-100.        ],
        [ -81.24892938],
        [-100.        ],
        [-100.        ],
        [ 100.        ],
        [  86.33326096],
        [ 100.        ],
        [  60.6314977 ],
        [ -95.46164691]]),
 array([[ -93.17045065, -100.        ,  100.  

In [ ]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

In [ ]:

def get_accuracy(predictions, Y):
    #print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

In [ ]:
start = t.time()
predecitions  = make_predictions(X_train,W1, b1, W2, b2)
print(get_accuracy(predecitions, Y_train))
end = t.time()
print("the time  expended for prediction using Krill Herd" , end -start)

0.9333333333333333
the time  expended for prediction using Krill Herd 0.0032835006713867188


<ipython-input-502-b705f9cde714>:12: RuntimeWarning: overflow encountered in exp
  A = np.exp(Z) / sum(np.exp(Z))
<ipython-input-502-b705f9cde714>:12: RuntimeWarning: invalid value encountered in divide
  A = np.exp(Z) / sum(np.exp(Z))


In [ ]:
dev_predictions = make_predictions(X_dev, W1, b1, W2, b2)
get_accuracy(dev_predictions, Y_dev)

<ipython-input-502-b705f9cde714>:12: RuntimeWarning: overflow encountered in exp
  A = np.exp(Z) / sum(np.exp(Z))
<ipython-input-502-b705f9cde714>:12: RuntimeWarning: invalid value encountered in divide
  A = np.exp(Z) / sum(np.exp(Z))


0.9666666666666667

In [ ]:
test_prediction(0, W1, b1, W2, b2)
test_prediction(1, W1, b1, W2, b2)
test_prediction(2, W1, b1, W2, b2)
test_prediction(3, W1, b1, W2, b2)

Prediction:  [1]
Label:  1
Prediction:  [1]
Label:  1
Prediction:  [1]
Label:  1
Prediction:  [1]
Label:  1


<ipython-input-502-b705f9cde714>:12: RuntimeWarning: overflow encountered in exp
  A = np.exp(Z) / sum(np.exp(Z))
<ipython-input-502-b705f9cde714>:12: RuntimeWarning: invalid value encountered in divide
  A = np.exp(Z) / sum(np.exp(Z))
